name: Deploy Documentation

on:
  push:
    branches:
      - master  # Adjust this to your default branch name if it's different (e.g., 'master')

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install mdBook
        run: |
          mkdir mdbook
          curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.40/mdbook-v0.4.40-x86_64-unknown-linux-gnu.tar.gz | tar -xzC ./mdbook
          echo "$(pwd)/mdbook" >> $GITHUB_PATH

      - name: Build with mdBook
        run: mdbook build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'book'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
